server:
  servlet:
    contextPath: /api/v1

spring:
  profiles:
    active: local # application-dev.yml 사용

# swagger
springdoc:
  swagger-ui:
    path: /index.html # Swagger-ui 경로
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json