server:
  servlet:
    contextPath: /api/v1

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL

  sql:
    init:
      mode: always
      data-locations:
        - classpath:member-data.sql
        - classpath:exchange-data.sql

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

# swagger
springdoc:
  swagger-ui:
    path: /index.html # Swagger-ui 경로
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion : none
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace