spring:
  config:
    import: application-secret.yml

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect # Hibernate가 스키마를 생성한 후에 데이터를 삽입
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:member-data.sql
        - classpath:exchange-data.sql


# AWS S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace