spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    show-sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace