spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/refooding_local
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# swagger
springdoc:
  api-docs:
    path: /api-docs # API 문서 생성 경로
  swagger-ui:
    path: /index.html # Swagger-ui 경로
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  cache:
    disabled: true
  override-with-generic-response: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: debug