server:
  servlet:
    contextPath: /api/v1

spring:
  config:
    import: application-secret.yml
  profiles:
    active: local # application-dev.yml 사용

# AWS S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

# swagger
springdoc:
  swagger-ui:
    path: /index.html # Swagger-ui 경로
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json