name : Deploy To Development Lightsail

on:
  push:
    branches: [ 'dev' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set YML
        run: echo "${{ secrets.APPLICATION_SECRET_PROPERTIES }}" > src/main/resources/application-secret.yml

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: SCP To Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: ${{ secrets.LIGHTSAIL_PORT }}
          source: "./build/libs/*SNAPSHOT.jar"
          target: /home/ubuntu/refooding-api/new

      - name: Deploy To Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          envs:
            APPLICATION_SECRET_PROPERTIES
          port: ${{ secrets.LIGHTSAIL_PORT }}
          script-stop: true
          script: |
            rm -rf /home/ubuntu/refooding-api/current
            mkdir /home/ubuntu/refooding-api/current
            mv /home/ubuntu/refooding-api/new/*SNAPSHOT.jar /home/ubuntu/refooding-api/current/*SNAPSHOT.jar
            cd /home/ubuntu/refooding-api/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar *SNAPSHOT.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/refooding-api/new
